import { useEffect, useMemo, useState } from 'react';
import { MapContainer, TileLayer, Marker, Circle, Popup, Polyline, Polygon, useMap } from 'react-leaflet';
import L from 'leaflet';
import { BookOpen, ChevronLeft, ChevronRight, Clock3, Compass, ExternalLink, Filter, MapPinned, Menu, Search, X } from 'lucide-react';
import { periods, sites, type Confidence, type Period, type Site, type SiteType } from './data';
import { historicalMaps, mapForYear } from './data/historicalMaps';

const center:[number,number] = [42.617, 23.515];
const icon = (color:string) => L.divIcon({className:'pin-wrap',html:`<span style="--pin:${color}" class="pin"></span>`,iconSize:[22,28],iconAnchor:[11,28]});
const colors:Record<Confidence,string> = {'Доказано':'#2f766f','Вероятно':'#c77c52','Предание':'#8c8a77'};
const oldOpacity=(site:Site, mode?:string)=>mode==='MODERN'?0.16:site.confidence==='Доказано'?0.85:0.5;
const yearLabel = (year:number) => year < 0 ? `${Math.abs(year)} пр. Хр.` : year === 2026 ? 'днес' : `${year} г.`;
function FlyTo({site}:{site:Site|null}) { const map=useMap(); if(site) map.flyTo([site.lat,site.lng],site.area?13:15,{duration:.7}); return null; }
function HistoricalLayers({year}:{year:number}) { const old=year<1944; const ancient=year<600; const medieval=year>=600&&year<1700; return <>{old&&<><Polyline positions={[[42.615,23.477],[42.626,23.496],[42.637,23.532]]} pathOptions={{color:'#92704f',weight:2,dashArray:ancient?'3 9':'8 5',opacity:.65}}/><Polyline positions={[[42.59,23.492],[42.603,23.515],[42.616,23.537]]} pathOptions={{color:'#557b73',weight:2,opacity:.55}}/><Polygon positions={[[42.584,23.469],[42.596,23.485],[42.607,23.477],[42.614,23.456],[42.6,23.443]]} pathOptions={{color:'#718d70',fillColor:'#718d70',fillOpacity:.1,weight:1}}/></>}{medieval&&<Polyline positions={[[42.601,23.515],[42.613,23.505],[42.626,23.497]]} pathOptions={{color:'#b4674f',weight:2,dashArray:'4 6',opacity:.8}}/>}</>; }

export default function App(){
 const urlYear=Number(new URLSearchParams(window.location.search).get('year')); const [period,setPeriod]=useState<Period>('Праистория'); const [year,setYear]=useState(Number.isFinite(urlYear)&&urlYear>=-5000&&urlYear<=2026?urlYear:-5000); const [active,setActive]=useState<Site|null>(null); const [query,setQuery]=useState(''); const [type,setType]=useState<SiteType|'Всички'>('Всички'); const [story,setStory]=useState(false); const [menu,setMenu]=useState(false); const [mapOverride,setMapOverride]=useState(''); const [compare,setCompare]=useState(false); const [split,setSplit]=useState(52); const [dragging,setDragging]=useState(false);
 const visible=useMemo(()=>sites.filter(s=>periods.findIndex(p=>p.label===s.period)<=periods.findIndex(p=>p.label===period) && (type==='Всички'||s.type===type) && `${s.title} ${s.description}`.toLowerCase().includes(query.toLowerCase())),[period,type,query]);
 useEffect(()=>{ if(active && !visible.some(site=>site.id===active.id)) setActive(visible[0] ?? null); },[visible,active]);
 const storyIndex=Math.max(0,sites.findIndex(s=>s.period===period)); const storySite=sites[storyIndex]||sites[0]; const mapState=mapOverride?historicalMaps.find(m=>m.id===mapOverride)??mapForYear(year):mapForYear(year);
 const selectPeriod=(p:Period)=>{setPeriod(p); const found=sites.find(s=>s.period===p); if(found)setActive(found)}; const changeYear=(next:number)=>{setYear(next);setMapOverride('');const p=periods.reduce((acc,x)=>next>=x.start?x:acc,periods[0]);setPeriod(p.label);window.history.replaceState({},'',`/?year=${next}`)};
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">Л</span><div><strong>Лозен</strong><small>през времето</small></div></div><div className="topbar-meta"><span>София · 42°37′ N</span><button className="icon-button menu-button" onClick={()=>setMenu(!menu)} aria-label="Меню"><Menu size={19}/></button></div></header>
  <main className="workspace">
   <aside className={`sidebar ${menu?'is-open':''}`}>
    <div className="intro"><p className="eyebrow">Дигитален исторически атлас</p><h1>Едно място.<br/><em>Много времена.</em></h1><p className="lede">Разходка през следите, храмовете и паметта на Лозен — от халколита до днес.</p></div>
    <div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Търси обект или период…" aria-label="Търси обект или период"/>{query&&<button onClick={()=>setQuery('')} aria-label="Изчисти"><X size={14}/></button>}</div>
    <div className="side-section"><div className="section-label"><span>Периоди</span><span className="count">{visible.length} обекта</span></div>{periods.map(p=><button key={p.label} className={`period-row ${period===p.label?'selected':''}`} onClick={()=>selectPeriod(p.label)}><span className="period-dot" style={{background:p.color}}/><span>{p.label}</span><small>{p.start<0?`${Math.abs(p.start)} пр.Хр.`:p.start} — {p.end===2026?'днес':p.end}</small></button>)}</div>
    <div className="side-section filters"><div className="section-label"><span><Filter size={13}/> Тип обект</span></div><select value={type} onChange={e=>setType(e.target.value as SiteType|'Всички')} aria-label="Филтрирай по тип"><option>Всички</option><option>Археология</option><option>Християнско наследство</option><option>Селище</option><option>Път и вода</option></select></div>
    <button className={`story-button ${story?'active':''}`} onClick={()=>setStory(!story)}><BookOpen size={17}/><span>{story?'Изход от историята':'Влез в историята'}</span><ChevronRight size={16}/></button>
    <footer className="sidebar-footer"><span><span className="legend-dot proven"/> доказано</span><span><span className="legend-dot probable"/> вероятно</span><span><span className="legend-dot oral"/> предание</span></footer>
   </aside>
   <section className="map-stage" aria-label="Интерактивна историческа карта">
    <div className="map-caption"><span className="live-dot"/> <span>Лозен · исторически пластове</span><span className="caption-rule"/><span>{mapState?.label}</span></div>
    <div className="map-selector"><span>КАРТА</span><select value={mapOverride||'auto'} onChange={e=>{const id=e.target.value;if(id==='auto'){setMapOverride('');return}const m=historicalMaps.find(x=>x.id===id);if(m){setMapOverride(id);changeYear(m.year)}}} aria-label="Избери картографски слой"><option value="auto">Автоматично</option>{historicalMaps.filter(m=>m.implemented).map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div>
    <div className="map-stack" onPointerMove={e=>{if(dragging){const r=e.currentTarget.getBoundingClientRect();setSplit(Math.max(8,Math.min(92,((e.clientX-r.left)/r.width)*100)))}}} onPointerUp={()=>setDragging(false)} onPointerLeave={()=>setDragging(false)}><MapContainer center={center} zoom={13} zoomControl={false} className="map"><TileLayer opacity={mapState?.mode==='MODERN'?1:(mapState?.id==='reconstruction-1910'||mapState?.id==='reconstruction-1898'?0.12:0)} attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><HistoricalLayers year={year}/>{visible.map(s=>s.area?<Circle key={s.id} center={[s.lat,s.lng]} radius={s.area*110} pathOptions={{color:colors[s.confidence],fillColor:colors[s.confidence],fillOpacity:oldOpacity(s,mapState?.mode),weight:1.5,dashArray:'5 5'}} eventHandlers={{click:()=>setActive(s)}}/>:<Marker key={s.id} position={[s.lat,s.lng]} icon={icon(colors[s.confidence])} eventHandlers={{click:()=>setActive(s)}}><Popup>{s.title}</Popup></Marker>)}<Polyline positions={[[42.6219,23.5108],[42.6034,23.5153]]} pathOptions={{color:'#c49b55',weight:2,dashArray:'5 8',opacity:mapState?.mode==='MODERN'?.7:.55}}/><FlyTo site={active}/></MapContainer>{compare&&<div className="compare-map" style={{clipPath:`inset(0 0 0 ${split}%)`}}><MapContainer center={center} zoom={13} zoomControl={false} dragging={false} scrollWheelZoom={false} doubleClickZoom={false} className="map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/></MapContainer></div>}{compare&&<div className="compare-divider" style={{left:`${split}%`}} onPointerDown={()=>setDragging(true)}><span>ДНЕС</span></div>}</div>
    <div className="map-controls"><button onClick={()=>setActive(null)} aria-label="Центрирай карта"><Compass size={18}/></button><span/><button className={compare?'active':''} onClick={()=>setCompare(!compare)} aria-label="Сравни стара и съвременна карта"><Clock3 size={17}/></button></div>
    {story&&<div className="story-card"><div className="story-kicker"><Clock3 size={14}/> Историята на място</div><h2>{storySite.title}</h2><p>{storySite.description}</p><button onClick={()=>setActive(storySite)}>Отвори обекта <ChevronRight size={15}/></button><div className="story-nav"><button onClick={()=>{const i=Math.max(0,storyIndex-1);selectPeriod(sites[i].period)}} aria-label="Предишен"><ChevronLeft size={17}/></button><span>{storyIndex+1} / {sites.length}</span><button onClick={()=>{const i=Math.min(sites.length-1,storyIndex+1);selectPeriod(sites[i].period)}} aria-label="Следващ"><ChevronRight size={17}/></button></div></div>}
    <div className="timeline"><div className="timeline-label"><span>Път през времето</span><strong>{yearLabel(year)}</strong></div><input type="range" min="-5000" max="2026" step="1" value={year} onChange={e=>changeYear(Number(e.target.value))} aria-label="Година"/><div className="ticks"><span>5000 пр.Хр.</span><span>0</span><span>1000</span><span>1500</span><span>1900</span><span>днес</span></div></div>
   </section>
   {active&&<aside className="detail-drawer"><button className="close-drawer" onClick={()=>setActive(null)} aria-label="Затвори"><X size={18}/></button><div className="detail-header" style={{'--accent':colors[active.confidence]} as React.CSSProperties}><span className="detail-type">{active.type}</span><div className="detail-icon">{active.type==='Археология'?'◈':active.type==='Християнско наследство'?'✦':'⌁'}</div></div><div className="detail-body"><span className="confidence" style={{color:colors[active.confidence]}}><i/> {active.confidence}</span><h2>{active.title}</h2><p className="detail-years">{active.years}</p><p>{active.description}</p><div className="location"><MapPinned size={15}/><span>{active.area?'Приблизителна зона':'Локализация по източник'}<small>{active.lat.toFixed(4)}° N · {active.lng.toFixed(4)}° E</small></span></div><div className="sources"><h3>Източници</h3>{active.sources.map(src=><a href={src.url} target="_blank" rel="noreferrer" key={src.label}>{src.label}<ExternalLink size={13}/></a>)}</div></div></aside>}
  </main>
 </div>
}
